#!/usr/bin/env bash


if [[ "$#" != "2" ]]
then 
  echo USAGE: filltemplate  CONFIGFILE TEMPLATEFILE
  exit 1
fi

 
CONFIGFILE="$1"
TEMPLATEFILE="$2"

if [[ ! -r "$TEMPLATEFILE" ]]
then 
  echo "ERROR: cannot read  template file '$TEMPLATEFILE'"
  exit 1
fi  

if [ ! "${TEMPLATEFILE: -4}" == ".tpl" ]
then 
  echo "ERROR: template file '$TEMPLATEFILE' does not have extension '.tpl'"
  exit 1
fi



OUTPUTFILE=${TEMPLATEFILE%.tpl}


if [[ ! -r "$CONFIGFILE" ]]
then 
  echo "ERROR: cannot read  template file '$CONFIGFILE'"
  exit 1
fi  

if [ ! "${CONFIGFILE: -5}" == ".bash" ]
then 
  echo "ERROR: config file '$CONFIGFILE' does not have extension '.bash'"
  exit 1
fi

cmdpath=$(command -v envsubst)
if [[  ! -x "$cmdpath" ]] 
then 
    echo "ERROR: missing required executable '/usr/bin/envsubst'."
    exit 1
fi

source $CONFIGFILE
vars=$(printf '${%s} ' $(cat "$CONFIGFILE"  | grep "export" | grep  '='  | cut -d'=' -f1 | sed 's/\s*export\s*//i'))
cat "$TEMPLATEFILE" | envsubst "$vars" > "$OUTPUTFILE" 
 