#!/usr/bin/env bash

# get paths
script_dir=$(dirname $0)
repo_dir=$(dirname "$script_dir")


# read in config
source "$script_dir/config.bash"

# create cookbook directories
mkdir -p "$repo_dir/data/cookbook/$CONFIG_COOKBOOK"
mkdir -p "$repo_dir/data/pub/$CONFIG_COOKBOOK"

# set cookbook in templates
$script_dir/filltemplate $script_dir/config.bash $script_dir/docker-compose.yml.tpl
$script_dir/filltemplate $script_dir/config.bash $script_dir/devcontainer.json.tpl


