#!/usr/bin/env bash

# get paths
script_dir=$(dirname $0)
repo_dir=$(dirname "$script_dir")

# read in config to get CONFIG_COOKBOOK set
source "$script_dir/config.bash"

# create cookbook directories
mkdir -p "$repo_dir/data/cookbook/$CONFIG_COOKBOOK"
mkdir -p "$repo_dir/data/pub/$CONFIG_COOKBOOK"

# initiate new cookbook with code from our default cookbook
cp "$repo_dir/data/cookbook/mycookbook/mycookbook.php" "$repo_dir/data/cookbook/$CONFIG_COOKBOOK/${CONFIG_COOKBOOK}.php"

# set cookbook in templates
$script_dir/filltemplate $script_dir/config.bash $script_dir/docker-compose.yml.tpl
$script_dir/filltemplate $script_dir/config.bash $script_dir/devcontainer.json.tpl

#  The $repo_dir/data/local/config.php loads $repo_dir/data/local/cookbook.php to load cookbooks
#  independent of other configuration. So we can just overwrite latter file:
echo "<?php

@include_once(\"\$FarmD/cookbook/$CONFIG_COOKBOOK/$CONFIG_COOKBOOK.php\");

" >"$repo_dir/data/local/cookbook.php"
