#!/usr/bin/env bash

# get paths
script_dir=$(dirname $(realpath "$0"))
repo_dir=$(dirname "$script_dir")

echo script_dir=$script_dir
echo repo_dir=$repo_dir

CONFIGFILE="$script_dir/config.bash"

# read in config to get CONFIG_COOKBOOK set
# shellcheck disable=SC1090
source "$CONFIGFILE"

# create cookbook directories
mkdir -p "$repo_dir/data/cookbook/${CONFIG_COOKBOOK_NAME_LC}"
mkdir -p "$repo_dir/data/pub/${CONFIG_COOKBOOK_NAME_LC}"

# generate files from templates
# - container configuration files with cookbook setup
"$script_dir"/filltemplate "$CONFIGFILE" "$script_dir"/templates/docker-compose.yml.tpl >"$script_dir"/docker-compose.yml
"$script_dir"/filltemplate "$CONFIGFILE" "$script_dir"/templates/devcontainer.json.tpl >"$script_dir"/devcontainer.json
# - configure cookbook loading and add default cookbook script
"$script_dir"/filltemplate "$CONFIGFILE" "$script_dir"/templates/includecookbook.php.tpl >"$repo_dir/data/local/includecookbook.php"
"$script_dir"/filltemplate "$CONFIGFILE" "$script_dir"/templates/cookbook.php.tpl >"$repo_dir/data/cookbook/${CONFIG_COOKBOOK_NAME_LC}/${CONFIG_COOKBOOK_NAME_LC}.php"
# - repository README
"$script_dir"/filltemplate "$CONFIGFILE" "$script_dir"/templates/README.md.tpl >"$repo_dir/README.md"
# - add wiki pages to document cookbook in wiki itself
"$script_dir"/filltemplate "$CONFIGFILE" "$script_dir"/templates/Main.SideBar.tpl >"$repo_dir/data/wiki.d/Main.SideBar"
"$script_dir"/filltemplate "$CONFIGFILE" "$script_dir"/templates/Main.HomePage.tpl >"$repo_dir/data/wiki.d/Main.HomePage"
"$script_dir"/filltemplate "$CONFIGFILE" "$script_dir"/templates/Main.Recipe.tpl >"$repo_dir/data/wiki.d/Main.${CONFIG_COOKBOOK_NAME}"

echo "generated files:
- $script_dir/docker-compose.yml
- $script_dir/devcontainer.json
- $repo_dir/data/local/includecookbook.php
- $repo_dir/data/cookbook/$CONFIG_COOKBOOK_NAME_LC/${CONFIG_COOKBOOK_NAME_LC}.php
- $repo_dir/README.md
- $repo_dir/data/wiki.d/Main.SideBar
- $repo_dir/data/wiki.d/Main.HomePage
- $repo_dir/data/wiki.d/Main.${CONFIG_COOKBOOK_NAME}
"
